name: git_it_app_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  card_swiper: ^3.0.1
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
